# Generated by Django 5.0 on 2026-03-04 09:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimetableSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('campus_id', models.IntegerField()),
                ('class_group_id', models.IntegerField()),
                ('day', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday')], max_length=3)),
                ('period', models.CharField(choices=[('1', 'Period 1'), ('2', 'Period 2'), ('3', 'Period 3'), ('4', 'Period 4'), ('5', 'Period 5'), ('6', 'Period 6'), ('7', 'Period 7'), ('8', 'Period 8')], max_length=1)),
                ('course_name', models.CharField(max_length=100)),
                ('teacher_name', models.CharField(blank=True, max_length=100)),
                ('room', models.CharField(blank=True, max_length=50)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['day', 'period'],
                'unique_together': {('campus_id', 'class_group_id', 'day', 'period')},
            },
        ),
    ]
