# Generated by Django 5.0 on 2026-02-18 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial_academic_structure'),
        ('kernel', '0009_harden_user_role_binding'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_info', models.JSONField(default=dict)),
                ('guardian_info', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campus', models.ForeignKey(help_text='Campus this record belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='kernel.campus')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdmissionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_payload', models.JSONField(default=dict)),
                ('form_schema_version', models.CharField(default='v1', max_length=50)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('TESTED', 'Tested'), ('INTERVIEWED', 'Interviewed'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('WAITLISTED', 'Waitlisted')], default='SUBMITTED', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('academic_program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.academicprogram')),
                ('campus', models.ForeignKey(help_text='Campus this record belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='kernel.campus')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='admissions.applicant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InterviewEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.TextField()),
                ('recommendation', models.CharField(max_length=50)),
                ('conducted_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='admissions.admissionapplication')),
                ('campus', models.ForeignKey(help_text='Campus this record belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='kernel.campus')),
                ('interviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conducted_interviews', to='kernel.person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdmissionDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('WAITLISTED', 'Waitlisted')], max_length=20)),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('comments', models.TextField(blank=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='admissions.admissionapplication')),
                ('campus', models.ForeignKey(help_text='Campus this record belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='kernel.campus')),
                ('decided_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kernel.person')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['campus'], name='admissions__campus__55d944_idx')],
            },
        ),
        migrations.CreateModel(
            name='AdmissionTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('total_score', models.FloatField(default=100.0)),
                ('percentile', models.FloatField(blank=True, null=True)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('source', models.CharField(default='Internal', max_length=100)),
                ('conducted_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='admissions.admissionapplication')),
                ('campus', models.ForeignKey(help_text='Campus this record belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='kernel.campus')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['campus'], name='admissions__campus__4b9c62_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='applicant',
            index=models.Index(fields=['campus'], name='admissions__campus__ecc4bf_idx'),
        ),
        migrations.AddIndex(
            model_name='admissionapplication',
            index=models.Index(fields=['campus'], name='admissions__campus__29a367_idx'),
        ),
        migrations.AddIndex(
            model_name='interviewevaluation',
            index=models.Index(fields=['campus'], name='admissions__campus__81381b_idx'),
        ),
    ]
