# Generated by Django 5.0 on 2026-05-06 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0002_admissionapplication_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionapplication',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('TESTED', 'Tested'), ('MERIT_LISTED', 'Merit Listed'), ('INTERVIEWED', 'Interviewed'), ('INTERVIEW_PASSED', 'Interview Passed'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('WAITLISTED', 'Waitlisted'), ('ENROLLED', 'Enrolled')], default='SUBMITTED', max_length=20),
        ),
    ]
