# Generated by Django 5.0 on 2026-05-06 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_academicprogram_description'),
        ('admissions', '0003_alter_admissionapplication_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campus_id', models.IntegerField()),
                ('interview_type', models.CharField(choices=[('QUALIFYING', 'Qualifying Only (Pass/Fail)'), ('SCORED', 'Scored (Marks Based)')], default='QUALIFYING', max_length=20)),
                ('test_weight', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('interview_weight', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission_configs', to='academics.academicprogram')),
            ],
            options={
                'unique_together': {('campus_id', 'academic_program')},
            },
        ),
    ]
