# Generated by Django 5.0 on 2026-05-06 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0004_admissionconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionapplication',
            name='interview_marks',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='merit_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
