# Generated by Django 5.0 on 2026-03-12 09:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kernel', '0009_harden_user_role_binding'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampusIDConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campus_id', models.IntegerField(unique=True)),
                ('prefix', models.CharField(blank=True, default='', help_text="Optional prefix, e.g. 'GCQ'. Leave blank for numeric-only IDs.", max_length=20)),
                ('padding', models.PositiveIntegerField(default=6, help_text='Zero-pad width for the sequence number.')),
                ('current_sequence', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CampusPerson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('campus_id', models.IntegerField(db_index=True)),
                ('campus_identifier', models.CharField(help_text='Permanent campus ID, e.g. GCQ-000001. Immutable once set.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campus_memberships', to='kernel.person')),
            ],
            options={
                'unique_together': {('campus_id', 'campus_identifier'), ('campus_id', 'person')},
            },
        ),
    ]
