# Generated by Django 5.0 on 2026-02-17 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kernel', '0009_harden_user_role_binding'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50)),
                ('program_type', models.CharField(choices=[('PRIMARY', 'Primary Education'), ('SECONDARY', 'Secondary Education'), ('COLLEGE', 'College / Intermediate'), ('UNIVERSITY', 'University / Higher Ed')], max_length=20)),
                ('duration_years', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campus', models.ForeignKey(help_text='Campus this record belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='kernel.campus')),
            ],
            options={
                'verbose_name': 'Academic Program',
                'verbose_name_plural': 'Academic Programs',
                'db_table': 'academic_programs',
            },
        ),
        migrations.CreateModel(
            name='AcademicCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sequence', models.IntegerField(help_text='ordering sequence (1, 2, 3...)')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campus', models.ForeignKey(help_text='Campus this record belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='kernel.campus')),
                ('academic_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycles', to='academics.academicprogram')),
            ],
            options={
                'verbose_name': 'Academic Cycle',
                'verbose_name_plural': 'Academic Cycles',
                'db_table': 'academic_cycles',
                'ordering': ['sequence'],
                'unique_together': {('academic_program', 'name'), ('academic_program', 'sequence')},
            },
        ),
        migrations.CreateModel(
            name='AssessmentScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campus', models.ForeignKey(help_text='Campus this record belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='kernel.campus')),
            ],
            options={
                'verbose_name': 'Assessment Scheme',
                'verbose_name_plural': 'Assessment Schemes',
                'db_table': 'academic_assessment_schemes',
            },
        ),
        migrations.CreateModel(
            name='AssessmentPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sequence', models.IntegerField()),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment_scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='academics.assessmentscheme')),
            ],
            options={
                'verbose_name': 'Assessment Period',
                'verbose_name_plural': 'Assessment Periods',
                'db_table': 'academic_assessment_periods',
                'ordering': ['sequence'],
                'unique_together': {('assessment_scheme', 'sequence')},
            },
        ),
        migrations.AddField(
            model_name='academicprogram',
            name='assessment_scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programs', to='academics.assessmentscheme'),
        ),
        migrations.CreateModel(
            name='ClassGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('section', models.CharField(blank=True, max_length=50, null=True)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_groups', to='academics.academiccycle')),
                ('campus', models.ForeignKey(help_text='Campus this record belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='kernel.campus')),
            ],
            options={
                'verbose_name': 'Class Group',
                'verbose_name_plural': 'Class Groups',
                'db_table': 'academic_class_groups',
                'unique_together': {('academic_cycle', 'name', 'section')},
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campus', models.ForeignKey(help_text='Campus this record belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='kernel.campus')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'db_table': 'academic_courses',
                'unique_together': {('campus', 'code')},
            },
        ),
        migrations.CreateModel(
            name='CourseOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_required', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_offerings', to='academics.academicprogram')),
                ('campus', models.ForeignKey(help_text='Campus this record belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='kernel.campus')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='academics.course')),
            ],
            options={
                'verbose_name': 'Course Offering',
                'verbose_name_plural': 'Course Offerings',
                'db_table': 'academic_course_offerings',
                'unique_together': {('course', 'academic_program')},
            },
        ),
        migrations.CreateModel(
            name='AssessmentInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('conducted_date', models.DateField(blank=True, null=True)),
                ('max_marks', models.DecimalField(decimal_places=2, max_digits=6)),
                ('is_retake', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('CONDUCTED', 'Conducted'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campus', models.ForeignKey(help_text='Campus this record belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='kernel.campus')),
                ('assessment_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='academics.assessmentperiod')),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_instances', to='academics.classgroup')),
                ('course_offering', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_instances', to='academics.courseoffering')),
            ],
            options={
                'verbose_name': 'Assessment Instance',
                'verbose_name_plural': 'Assessment Instances',
                'db_table': 'academic_assessment_instances',
                'unique_together': {('class_group', 'assessment_period', 'course_offering', 'scheduled_date')},
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_number', models.CharField(max_length=50)),
                ('admission_date', models.DateField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('GRADUATED', 'Graduated'), ('WITHDRAWN', 'Withdrawn'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_profiles', to='academics.academicprogram')),
                ('campus', models.ForeignKey(help_text='Campus this record belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='kernel.campus')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_profiles', to='kernel.person')),
            ],
            options={
                'verbose_name': 'Student Profile',
                'verbose_name_plural': 'Student Profiles',
                'db_table': 'academic_student_profiles',
                'unique_together': {('campus', 'admission_number')},
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('WITHDRAWN', 'Withdrawn'), ('TRANSFERRED', 'Transferred')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campus', models.ForeignKey(help_text='Campus this record belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='kernel.campus')),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='academics.classgroup')),
                ('student_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='academics.studentprofile')),
            ],
            options={
                'verbose_name': 'Enrollment',
                'verbose_name_plural': 'Enrollments',
                'db_table': 'academic_enrollments',
                'unique_together': {('student_profile', 'class_group')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='academicprogram',
            unique_together={('campus', 'code')},
        ),
        migrations.CreateModel(
            name='AssessmentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_obtained', models.DecimalField(decimal_places=2, max_digits=6)),
                ('is_absent', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('entered_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment_instance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='academics.assessmentinstance')),
                ('campus', models.ForeignKey(help_text='Campus this record belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='kernel.campus')),
                ('entered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entered_results', to='kernel.person')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='academics.enrollment')),
            ],
            options={
                'verbose_name': 'Assessment Result',
                'verbose_name_plural': 'Assessment Results',
                'db_table': 'academic_assessment_results',
                'unique_together': {('enrollment', 'assessment_instance')},
            },
        ),
        migrations.CreateModel(
            name='TeachingAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_from', models.DateField(blank=True, null=True)),
                ('assigned_until', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campus', models.ForeignKey(help_text='Campus this record belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='kernel.campus')),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_assignments', to='academics.classgroup')),
                ('course_offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_assignments', to='academics.courseoffering')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teaching_assignments', to='kernel.person')),
            ],
            options={
                'verbose_name': 'Teaching Assignment',
                'verbose_name_plural': 'Teaching Assignments',
                'db_table': 'academic_teaching_assignments',
                'unique_together': {('class_group', 'course_offering', 'teacher')},
            },
        ),
    ]
