# Generated by Django 5.0 on 2026-04-12 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial_academic_structure'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicprogram',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
