# Generated by Django 5.0 on 2026-02-12 11:04

import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import kernel.models.user_account
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Campus name', max_length=255, unique=True)),
                ('campus_type', models.CharField(choices=[('PHYSICAL', 'Physical Campus'), ('VIRTUAL', 'Virtual Campus'), ('DEPARTMENT', 'Department')], default='PHYSICAL', help_text='Type of campus', max_length=20)),
                ('address', models.TextField(blank=True, help_text='Physical address if applicable', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this campus is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Campus',
                'verbose_name_plural': 'Campuses',
                'db_table': 'kernel_campuses',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('CAMPUS_ADMIN', 'Campus Admin'), ('REGISTRAR', 'Registrar'), ('FACULTY', 'Faculty'), ('STUDENT', 'Student'), ('PARENT', 'Parent'), ('ACCOUNTANT', 'Accountant'), ('LIBRARIAN', 'Librarian'), ('SECURITY', 'Security')], help_text='Role name', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Role description', null=True)),
                ('is_system_role', models.BooleanField(default=True, help_text='True if this is a predefined system role')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'db_table': 'kernel_roles',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(help_text="Unique permission code (e.g., 'kernel.view_person')", max_length=100, unique=True)),
                ('name', models.CharField(help_text='Human-readable permission name', max_length=255)),
                ('module', models.CharField(help_text="Module this permission belongs to (e.g., 'kernel', 'academics')", max_length=50)),
                ('description', models.TextField(blank=True, help_text='Detailed description of what this permission allows', null=True)),
                ('is_dangerous', models.BooleanField(default=False, help_text='True if this permission grants destructive capabilities')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
                'db_table': 'kernel_permissions',
                'indexes': [models.Index(fields=['module'], name='idx_permission_module')],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Immutable UUID for this person', primary_key=True, serialize=False)),
                ('full_name', models.CharField(help_text='Full legal name', max_length=255)),
                ('primary_email', models.EmailField(blank=True, help_text='Primary email address', max_length=254, null=True, unique=True)),
                ('primary_phone', models.CharField(help_text='Primary phone number with country code', max_length=20, unique=True)),
                ('date_of_birth', models.DateField(blank=True, help_text='Date of birth', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='False if person is no longer associated with institution')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'Persons',
                'db_table': 'kernel_persons',
                'indexes': [models.Index(fields=['primary_email'], name='idx_person_email'), models.Index(fields=['primary_phone'], name='idx_person_phone')],
            },
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_locked', models.BooleanField(default=False, help_text='True if account is locked')),
                ('failed_login_attempts', models.IntegerField(default=0, help_text='Failed login count')),
                ('lockout_until', models.DateTimeField(blank=True, help_text='Locked until this time', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('person', models.ForeignKey(blank=True, help_text='The person this account belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_accounts', to='kernel.person')),
            ],
            options={
                'verbose_name': 'User Account',
                'verbose_name_plural': 'User Accounts',
                'db_table': 'kernel_user_accounts',
            },
            managers=[
                ('objects', kernel.models.user_account.UserAccountManager()),
            ],
        ),
        migrations.CreateModel(
            name='RolePermissionMap',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.ForeignKey(blank=True, help_text='Who granted this permission', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('permission', models.ForeignKey(help_text='The permission', on_delete=django.db.models.deletion.CASCADE, related_name='role_maps', to='kernel.permission')),
                ('role', models.ForeignKey(help_text='The role', on_delete=django.db.models.deletion.CASCADE, related_name='permission_maps', to='kernel.role')),
            ],
            options={
                'verbose_name': 'Role Permission Map',
                'verbose_name_plural': 'Role Permission Maps',
                'db_table': 'kernel_role_permission_map',
            },
        ),
        migrations.CreateModel(
            name='UserRoleBinding',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('valid_from', models.DateTimeField(help_text='Role is valid from this date')),
                ('valid_until', models.DateTimeField(blank=True, help_text='Role is valid until this date (null = indefinite)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this binding is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('campus', models.ForeignKey(help_text='The campus where this role applies', on_delete=django.db.models.deletion.CASCADE, related_name='user_bindings', to='kernel.campus')),
                ('person', models.ForeignKey(help_text='The person', on_delete=django.db.models.deletion.CASCADE, related_name='role_bindings', to='kernel.person')),
                ('role', models.ForeignKey(help_text='The role', on_delete=django.db.models.deletion.CASCADE, related_name='user_bindings', to='kernel.role')),
            ],
            options={
                'verbose_name': 'User Role Binding',
                'verbose_name_plural': 'User Role Bindings',
                'db_table': 'kernel_user_role_bindings',
            },
        ),
        migrations.CreateModel(
            name='BiometricIdentity',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('biometric_type', models.CharField(choices=[('FINGERPRINT', 'Fingerprint'), ('FACE', 'Face Recognition'), ('IRIS', 'Iris Scan')], help_text='Type of biometric data', max_length=20)),
                ('encoding', models.BinaryField(help_text='Encrypted biometric template/encoding')),
                ('quality_score', models.FloatField(blank=True, help_text='Quality score of the biometric sample (0-100)', null=True)),
                ('enrollment_device_id', models.CharField(blank=True, help_text='ID of device used for enrollment', max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this biometric is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('person', models.ForeignKey(help_text='The person this biometric belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='biometric_identities', to='kernel.person')),
            ],
            options={
                'verbose_name': 'Biometric Identity',
                'verbose_name_plural': 'Biometric Identities',
                'db_table': 'kernel_biometric_identities',
                'indexes': [models.Index(fields=['person', 'biometric_type'], name='idx_biometric_person_type')],
            },
        ),
        migrations.AddIndex(
            model_name='useraccount',
            index=models.Index(fields=['username'], name='idx_useraccount_username'),
        ),
        migrations.AddIndex(
            model_name='useraccount',
            index=models.Index(fields=['email'], name='idx_useraccount_email'),
        ),
        migrations.AlterUniqueTogether(
            name='rolepermissionmap',
            unique_together={('role', 'permission')},
        ),
        migrations.AddIndex(
            model_name='userrolebinding',
            index=models.Index(fields=['person', 'campus'], name='idx_binding_person_campus'),
        ),
        migrations.AddIndex(
            model_name='userrolebinding',
            index=models.Index(fields=['valid_from', 'valid_until'], name='idx_binding_validity'),
        ),
        migrations.AlterUniqueTogether(
            name='userrolebinding',
            unique_together={('person', 'role', 'campus', 'valid_from')},
        ),
    ]
