# Generated by Django 5.0 on 2026-02-12 16:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kernel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(db_index=True, help_text="Name of the action (e.g., 'create_student', 'login_attempt')", max_length=255)),
                ('target_type', models.CharField(blank=True, db_index=True, help_text="Type of the target entity (e.g., 'Student', 'Course')", max_length=255, null=True)),
                ('target_id', models.CharField(blank=True, db_index=True, help_text='ID of the target entity', max_length=255, null=True)),
                ('changes', models.JSONField(blank=True, help_text="JSON delta of changes (e.g., {'old': ..., 'new': ...})", null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, unpack_ipv4=True)),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('result', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILURE', 'Failure'), ('DENIED', 'Denied')], db_index=True, default='SUCCESS', max_length=20)),
                ('reason', models.TextField(blank=True, help_text='Reason for failure or denial', null=True)),
                ('actor', models.ForeignKey(blank=True, help_text='The person who performed the action', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='kernel.person')),
                ('campus', models.ForeignKey(blank=True, help_text='The campus where the action occurred', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='kernel.campus')),
                ('role', models.ForeignKey(blank=True, help_text='The role assumed by the actor', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='kernel.role')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['actor', 'timestamp'], name='kernel_audi_actor_i_b5ac43_idx'), models.Index(fields=['action', 'timestamp'], name='kernel_audi_action_bd7a8d_idx'), models.Index(fields=['campus', 'timestamp'], name='kernel_audi_campus__932cb3_idx'), models.Index(fields=['target_type', 'target_id'], name='kernel_audi_target__f32ed6_idx')],
            },
        ),
    ]
