# Generated by Django 5.0 on 2026-02-13 19:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kernel", "0002_auditlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Friendly name for the device", max_length=100
                    ),
                ),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("FINGERPRINT_READER", "Fingerprint Reader"),
                            ("FACE_CAM", "Facial Recognition Camera"),
                            ("IRIS_SCANNER", "Iris Scanner"),
                        ],
                        max_length=20,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "driver_identifier",
                    models.CharField(
                        help_text="Hardware ID or Serial Number used by the driver",
                        max_length=100,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ONLINE", "Online"),
                            ("OFFLINE", "Offline"),
                            ("ERROR", "Error State"),
                        ],
                        default="OFFLINE",
                        max_length=10,
                    ),
                ),
                ("last_heartbeat", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "campus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devices",
                        to="kernel.campus",
                    ),
                ),
            ],
            options={
                "verbose_name": "Biometric Device",
                "verbose_name_plural": "Biometric Devices",
                "db_table": "kernel_devices",
                "indexes": [
                    models.Index(
                        fields=["campus", "device_type"],
                        name="kernel_devi_campus__3cda50_idx",
                    ),
                    models.Index(
                        fields=["driver_identifier"],
                        name="kernel_devi_driver__714109_idx",
                    ),
                ],
            },
        ),
    ]
