# Generated by Django 5.0 on 2026-02-14 07:59

from django.db import migrations
from django.contrib.postgres.operations import BtreeGistExtension

class Migration(migrations.Migration):

    dependencies = [
        ('kernel', '0003_device'),
    ]

    operations = [
        BtreeGistExtension(),
    ]
