# Generated by Django 5.0 on 2026-02-14 08:11

import django.contrib.postgres.fields.ranges
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kernel', '0004_install_btree_gist'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrolebinding',
            name='validity',
            field=django.contrib.postgres.fields.ranges.DateTimeRangeField(blank=True, help_text='Time range validation [start, end)', null=True),
        ),
    ]
