# Generated by Django 5.0 on 2026-02-14 08:11

from django.db import migrations
from django.contrib.postgres.fields import DateTimeRangeField
from psycopg2.extras import DateTimeTZRange

def migrate_data(apps, schema_editor):
    UserRoleBinding = apps.get_model('kernel', 'UserRoleBinding')
    for binding in UserRoleBinding.objects.all():
        binding.validity = DateTimeTZRange(binding.valid_from, binding.valid_until, bounds='[)')
        binding.save()

class Migration(migrations.Migration):

    dependencies = [
        ('kernel', '0005_add_validity_field'),
    ]

    operations = [
        migrations.RunPython(migrate_data),
    ]
