# Generated by Django 5.0 on 2026-02-14 08:17

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import kernel.models.user_role_binding
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kernel', '0006_migrate_binding_data'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='userrolebinding',
            name='idx_binding_validity',
        ),
        migrations.AlterUniqueTogether(
            name='userrolebinding',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='userrolebinding',
            name='validity',
            field=django.contrib.postgres.fields.ranges.DateTimeRangeField(default=kernel.models.user_role_binding.default_validity, help_text='Time range validation [start, end)'),
        ),
        migrations.AddConstraint(
            model_name='userrolebinding',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(expressions=[('person', '='), ('role', '='), ('campus', '='), ('validity', '&&')], name='exclude_overlapping_role_bindings'),
        ),
        migrations.RemoveField(
            model_name='userrolebinding',
            name='valid_from',
        ),
        migrations.RemoveField(
            model_name='userrolebinding',
            name='valid_until',
        ),
    ]
