# Generated by Django 5.0 on 2026-02-14 08:19

import django.contrib.postgres.fields.ranges
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kernel', '0007_remove_legacy_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrolebinding',
            name='validity',
            field=django.contrib.postgres.fields.ranges.DateTimeRangeField(help_text='Time range validation [start, end)'),
        ),
    ]
