# Generated by Django 5.0 on 2026-02-17 08:12

import django.contrib.postgres.fields.ranges
import kernel.models.user_role_binding
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kernel', '0008_clean_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrolebinding',
            name='validity',
            field=django.contrib.postgres.fields.ranges.DateTimeRangeField(default=kernel.models.user_role_binding.default_validity, help_text='Time range validation [start, end)'),
        ),
    ]
