# Generated by Django 5.0 on 2026-03-10 08:17

import modules.media.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('campus_id', models.IntegerField(db_index=True)),
                ('entity_type', models.CharField(max_length=64)),
                ('asset_type', models.CharField(max_length=64)),
                ('entity_id', models.CharField(max_length=64)),
                ('file', models.FileField(upload_to=modules.media.models._upload_to)),
                ('mime_type', models.CharField(max_length=64)),
                ('file_size', models.PositiveIntegerField(help_text='Size in bytes')),
                ('uploaded_by_id', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
