# Generated by Django 5.0 on 2026-02-19 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kernel', '0009_harden_user_role_binding'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkforceAttendanceDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('device_type', models.CharField(choices=[('FINGERPRINT', 'Fingerprint'), ('FACE', 'Face'), ('HYBRID', 'Hybrid')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('api_token', models.CharField(help_text='Secret token for device authentication', max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campus', models.ForeignKey(help_text='Campus this record belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='kernel.campus')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkforceAttendanceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('CHECK_IN', 'Check In'), ('CHECK_OUT', 'Check Out')], max_length=20)),
                ('event_time', models.DateTimeField()),
                ('source', models.CharField(choices=[('FINGERPRINT', 'Fingerprint'), ('FACE', 'Face'), ('MANUAL', 'Manual Override')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campus', models.ForeignKey(help_text='Campus this record belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='kernel.campus')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='workforce.workforceattendancedevice')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workforce_events', to='kernel.person')),
            ],
        ),
        migrations.CreateModel(
            name='WorkforceDailyAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('first_check_in', models.DateTimeField(blank=True, null=True)),
                ('last_check_out', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campus', models.ForeignKey(help_text='Campus this record belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='kernel.campus')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workforce_daily_attendance', to='kernel.person')),
            ],
        ),
        migrations.AddIndex(
            model_name='workforceattendancedevice',
            index=models.Index(fields=['campus'], name='workforce_w_campus__ab69df_idx'),
        ),
        migrations.AddIndex(
            model_name='workforceattendanceevent',
            index=models.Index(fields=['person', 'event_time'], name='workforce_w_person__7e162e_idx'),
        ),
        migrations.AddIndex(
            model_name='workforceattendanceevent',
            index=models.Index(fields=['campus', 'event_time'], name='workforce_w_campus__5a00e9_idx'),
        ),
        migrations.AddConstraint(
            model_name='workforcedailyattendance',
            constraint=models.UniqueConstraint(fields=('person', 'date'), name='unique_workforce_daily_attendance'),
        ),
    ]
