# Generated by Django 5.0 on 2026-02-19 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial_academic_structure'),
        ('kernel', '0009_harden_user_role_binding'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField()),
                ('session_type', models.CharField(choices=[('DAILY', 'Daily'), ('PERIOD', 'Period'), ('SUBJECT', 'Subject')], default='DAILY', max_length=20)),
                ('source', models.CharField(choices=[('MANUAL', 'Manual'), ('BIOMETRIC', 'Biometric'), ('FACIAL', 'Facial')], default='MANUAL', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campus', models.ForeignKey(help_text='Campus this record belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='kernel.campus')),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_sessions', to='academics.classgroup')),
                ('course_offering', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_sessions', to='academics.courseoffering')),
                ('taken_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='taken_attendance_sessions', to='kernel.person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LATE', 'Late'), ('EXCUSED', 'Excused')], max_length=20)),
                ('marked_at', models.DateTimeField(auto_now_add=True)),
                ('campus', models.ForeignKey(help_text='Campus this record belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='kernel.campus')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='academics.studentprofile')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='attendance.attendancesession')),
            ],
        ),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['campus'], name='attendance__campus__3a4f40_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.UniqueConstraint(fields=('session', 'student'), name='unique_session_student_attendance'),
        ),
    ]
